# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-20 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0002_remove_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=5),
            preserve_default=False,
        ),
    ]
